# Generated by Django 3.1 on 2021-03-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_profile_spacing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='editor',
            field=models.CharField(blank=True, choices=[('Project 1', 'Project 1'), ('Project 2', 'Project 2'), ('Project 3', 'Project 3'), ('Project 4', 'Project 4')], default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='os',
            field=models.CharField(blank=True, choices=[('BTech', 'BTech'), ('MTech', 'MTech'), ('Other', 'Other')], default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spacing',
            field=models.CharField(blank=True, choices=[('Tabs', 'Tabs'), ('Spaces', 'Spaces')], default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tech_stack',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
